# Generated by Django 5.1.4 on 2026-04-28 02:34

import apps.questions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='file_path',
            field=models.FileField(max_length=500, upload_to=apps.questions.models._pdf_upload_path),
        ),
    ]
