# Generated by Django 5.1.4 on 2026-06-19 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions.pdfdocument'),
        ),
    ]
