# Generated by Django 5.1.4 on 2026-06-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_source_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rationale',
            field=models.TextField(blank=True),
        ),
    ]
