# Generated by Django 5.1.4 on 2026-06-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_rationale'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='file_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
