# Generated by Django 5.1.4 on 2026-06-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_pdfdocument_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_indices',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Opción única'), ('true_false', 'Verdadero/Falso'), ('multiple', 'Opción múltiple')], default='single', max_length=12),
        ),
    ]
