# Generated by Django 5.1.4 on 2026-06-24 04:25

from django.db import migrations


def backfill(apps, schema_editor):
    Question = apps.get_model('questions', 'Question')
    for q in Question.objects.all():
        if not q.correct_indices:
            # Las preguntas existentes son todas de opción única; question_type
            # ya quedó en 'single' por el default del campo.
            q.correct_indices = [q.correct_index]
            q.save(update_fields=['correct_indices'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_question_correct_indices_question_question_type'),
    ]

    operations = [
        migrations.RunPython(backfill, noop),
    ]
