# Generated by Django 5.1.4 on 2026-06-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_backfill_question_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='cognitive_level',
            field=models.CharField(blank=True, choices=[('recordar', 'Recordar'), ('comprender', 'Comprender'), ('aplicar', 'Aplicar'), ('analizar', 'Analizar'), ('evaluar', 'Evaluar'), ('crear', 'Crear')], default='', max_length=12),
        ),
    ]
