# Generated by Django 5.1.4 on 2026-07-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_question_cognitive_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgenode',
            name='questions_per_session',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
