# Generated by Django 5.1.4 on 2026-04-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=20)),
                ('risk_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('risk_nodes', models.JSONField(default=list)),
                ('prediction', models.FloatField()),
                ('reasoning', models.TextField()),
                ('recommendation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BKTState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_mastery', models.FloatField(default=0.3)),
                ('p_transit', models.FloatField(default=0.09)),
                ('p_slip', models.FloatField(default=0.1)),
                ('p_guess', models.FloatField(default=0.2)),
                ('attempts', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlindSpotIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipc', models.FloatField()),
                ('students_count', models.IntegerField()),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CognitiveIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declared_confidence', models.FloatField()),
                ('bkt_mastery', models.FloatField()),
                ('icc', models.FloatField()),
                ('gap', models.FloatField()),
                ('profile', models.CharField(choices=[('overconfident', 'Overconfident'), ('underconfident', 'Underconfident'), ('calibrated', 'Calibrated')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
