# Generated by Django 5.1.4 on 2026-04-20 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cognitive', '0001_initial'),
        ('evaluation_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidiagnosis',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_diagnoses', to='evaluation_sessions.evaluationsession'),
        ),
    ]
