# Generated by Django 5.1.4 on 2026-06-08 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cognitive', '0002_initial'),
        ('evaluation_sessions', '0003_initial'),
        ('questions', '0002_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aidiagnosis',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_diagnoses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bktstate',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bkt_states', to='questions.knowledgenode'),
        ),
        migrations.AddField(
            model_name='bktstate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bkt_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blindspotindex',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blind_spots', to='questions.knowledgenode'),
        ),
        migrations.AddField(
            model_name='blindspotindex',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blind_spots', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='cognitiveindex',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_indices', to='questions.knowledgenode'),
        ),
        migrations.AddField(
            model_name='cognitiveindex',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cognitive_indices', to='evaluation_sessions.evaluationsession'),
        ),
        migrations.AddField(
            model_name='cognitiveindex',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_indices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprogresssnapshot',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_snapshots', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='studentprogresssnapshot',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_snapshots', to='evaluation_sessions.evaluationsession'),
        ),
        migrations.AddField(
            model_name='studentprogresssnapshot',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bktstate',
            unique_together={('student', 'node')},
        ),
        migrations.AddIndex(
            model_name='studentprogresssnapshot',
            index=models.Index(fields=['student', 'room', 'created_at'], name='cognitive_s_student_15e5d1_idx'),
        ),
    ]
