# Generated by Django 5.1.4 on 2026-06-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidiagnosis',
            name='problem_type',
            field=models.CharField(blank=True, choices=[('vacio_conceptual', 'Vacío conceptual'), ('confusion_conceptual', 'Confusión entre conceptos'), ('error_procedimental', 'Error procedimental'), ('aplicacion_incorrecta', 'Aplicación incorrecta'), ('sin_patron', 'Sin patrón claro')], default='', max_length=24),
        ),
    ]
