# Generated by Django 5.1.4 on 2026-07-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cognitive', '0004_aidiagnosis_problem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidiagnosis',
            name='student_reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aidiagnosis',
            name='student_recommendation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
