# Generated by Django 5.1.4 on 2026-06-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation_sessions', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='answer',
            name='selected_indices',
            field=models.JSONField(default=list),
        ),
    ]
