# Generated by Django 5.1.4 on 2026-06-24 04:25

from django.db import migrations


def backfill(apps, schema_editor):
    Answer = apps.get_model('evaluation_sessions', 'Answer')
    for a in Answer.objects.all():
        changed = False
        if not a.selected_indices:
            a.selected_indices = [a.selected_index]
            changed = True
        # Las respuestas existentes son binarias: score = 1.0 si acertó.
        new_score = 1.0 if a.is_correct else 0.0
        if a.score != new_score:
            a.score = new_score
            changed = True
        if changed:
            a.save(update_fields=['selected_indices', 'score'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation_sessions', '0005_answer_score_answer_selected_indices'),
    ]

    operations = [
        migrations.RunPython(backfill, noop),
    ]
