# Generated by Django 5.1.4 on 2026-06-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation_sessions', '0006_backfill_question_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationsession',
            name='selected_node_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
