# Generated by Django 5.1.4 on 2026-07-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation_sessions', '0007_evaluationsession_selected_node_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationsession',
            name='node_quotas',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
