# Generated by Django 5.1.4 on 2026-06-18 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roommembership',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='roommembership',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='roommembership',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='rooms.section'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('room', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='roommembership',
            unique_together={('room', 'student')},
        ),
    ]
