# Generated by Django 5.1.4 on 2026-07-04 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_roomjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomjoinrequest',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_requests', to='rooms.section'),
        ),
    ]
