# Generated by Django 5.1.4 on 2026-06-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('question_pending', 'Preguntas por aprobar'), ('student_at_risk', 'Estudiante en riesgo'), ('diagnosis_ready', 'Diagnóstico listo'), ('room_joined', 'Te uniste a una sala'), ('questions_added', 'Preguntas nuevas en tu sala'), ('practice_reminder', 'Tienes práctica pendiente')], max_length=40),
        ),
    ]
