# Generated by Django 5.1.4 on 2026-07-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('question_pending', 'Preguntas por aprobar'), ('student_at_risk', 'Estudiante en riesgo'), ('diagnosis_ready', 'Diagnóstico listo'), ('room_joined', 'Te uniste a una sala'), ('questions_added', 'Preguntas nuevas en tu sala'), ('practice_reminder', 'Tienes práctica pendiente'), ('join_request', 'Solicitud de ingreso a tu sala'), ('join_rejected', 'Solicitud de ingreso rechazada')], max_length=40),
        ),
    ]
